### PR TITLE
fix: update styles when maintenance ended

### LINKED ISSUE #45: EndDate doesn't stop the Maintenance process
localhost: http://localhost:8383/maintenances

**actual result:** when setted endDate in the maintenance item and currentDate > EndDate, it still processing
current time 9PM

Image

### PR DESCRIPTION
**Pull request by KarinaOliinyk**
Fixes #45

### CODE REVIEW

File: apps/web/src/app/maintenance/components/maintenance-card.tsx [hunk 1]
```diff
@@ -60,40 +69,46 @@ const MaintenanceCard = ({
...
+                <Badge 
+                  variant="outline"
+                  className={isMaintenanceEnded ? "text-gray-500" : ""}
+                >
                   {getStrategyLabel(maintenance.strategy || "")}
                 </Badge>
               </div>
               {maintenance.description && (
-                <p className="text-sm text-muted-foreground mb-2 line-clamp-2">
+                <p className={`text-sm mb-2 line-clamp-2 ${isMaintenanceEnded ? "text-gray-500" : "text-muted-foreground"}`}>
```
Comment (0xfurai) [inline apps/web/src/app/maintenance/components/maintenance-card.tsx:89]: checkout out clsx tool for conditional classes
